import { Plus_Jakarta_Sans, Barlow_Condensed } from "next/font/google";
import type { Metadata } from "next";
import { Suspense } from "react";
import "@/styles/globals.css";
import InstallPrompt from "@/components/pwa/InstallPrompt";
import NotificationInitializer from "@/components/notification/NotificationInitializer";
import NotificationPrompt from "@/components/notification/NotificationPrompt";
import { ToastProvider } from "../contexts/ToastContext";
import AuthProvider from "@/components/common/AuthProvider";
import ToastContainer from "../components/toast/ToastContainer";
import SubscriptionSuccessHandler from "@/components/common/SubscriptionSuccessHandler";

// Import the required fonts
const plusJakartaSans = Plus_Jakarta_Sans({
  variable: "--font-plus-jakarta-sans",
  subsets: ["latin"],
  weight: ["200", "400", "500", "600", "700"], // Specify the weights you need
});

const barlowCondensed = Barlow_Condensed({
  variable: "--font-barlow-condensed",
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600"], // Specify the weights you need
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  manifest: "/manifest.webmanifest",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        suppressHydrationWarning
        className={`font-sans ${plusJakartaSans.variable} ${barlowCondensed.variable} antialiased`}
      >
        <ToastProvider>
          <AuthProvider>
            <InstallPrompt />
            <NotificationInitializer />
            <NotificationPrompt />
            <Suspense fallback={null}>
              <SubscriptionSuccessHandler />
            </Suspense>
            {children}
            <ToastContainer />
          </AuthProvider>
        </ToastProvider>
      </body>
    </html>
  );
}
