import { Plus_Jakarta_Sans, Barlow_Condensed } from "next/font/google";
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "@/styles/globals.css";
import InstallPrompt from "@/components/pwa/InstallPrompt";
import PushNotificationManager from "@/components/pwa/PushNotificationManager";
import { NotificationProvider } from "@/contexts/NotificationContext";
import AuthProvider from "@/components/AuthProvider";

// Import the required fonts
const plusJakartaSans = Plus_Jakarta_Sans({
  variable: "--font-plus-jakarta-sans",
  subsets: ["latin"],
  weight: ["200", "400", "500", "600", "700"], // Specify the weights you need
});

const barlowCondensed = Barlow_Condensed({
  variable: "--font-barlow-condensed",
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600"], // Specify the weights you need
});

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});
2;
const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  manifest: "/manifest.webmanifest",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        suppressHydrationWarning
        className={`font-sans ${plusJakartaSans.variable} ${geistSans.variable} ${geistMono.variable} ${barlowCondensed.variable} antialiased`}
      >
        <NotificationProvider>
          <AuthProvider>
            <InstallPrompt />
            {children}
          </AuthProvider>
        </NotificationProvider>
      </body>
    </html>
  );
}
