export const employees = [
  {
    id: "emp-001",
    name: "Darlene Robertson",
    job: "Cleaner",
    joiningDate: "9/23/16",
    totalHoursWork: "365 Hours",
    status: "Active",
  },
  {
    id: "emp-002",
    name: "Cody Fisher",
    job: "Yaya",
    joiningDate: "10/28/12",
    totalHoursWork: "225 Hours",
    status: "Inactive",
  },
  {
    id: "emp-003",
    name: "Savannah Nguyen",
    job: "Helper",
    joiningDate: "12/4/17",
    totalHoursWork: "115 Hours",
    status: "Inactive",
  },
  {
    id: "emp-004",
    name: "Floyd Miles",
    job: "Caregivers",
    joiningDate: "7/27/13",
    totalHoursWork: "65 Hours",
    status: "Active",
  },
  {
    id: "emp-005",
    name: "Jacob Jones",
    job: "Caregivers",
    joiningDate: "1/15/12",
    totalHoursWork: "41 Hours",
    status: "Inactive",
  },
  {
    id: "emp-006",
    name: "Marvin McKinney",
    job: "Cleaner",
    joiningDate: "3/4/16",
    totalHoursWork: "691 Hours",
    status: "Active",
  },
  {
    id: "emp-007",
    name: "Cameron Williamson",
    job: "Yaya",
    joiningDate: "8/15/17",
    totalHoursWork: "595 Hours",
    status: "Active",
  },
  {
    id: "emp-008",
    name: "Courtney Henry",
    job: "Driver",
    joiningDate: "5/7/16",
    totalHoursWork: "325 Hours",
    status: "Active",
  },
  {
    id: "emp-009",
    name: "Albert Flores",
    job: "Security",
    joiningDate: "4/12/15",
    totalHoursWork: "432 Hours",
    status: "Active",
  },
  {
    id: "emp-010",
    name: "Jenny Wilson",
    job: "Helper",
    joiningDate: "6/9/14",
    totalHoursWork: "198 Hours",
    status: "Inactive",
  },
  {
    id: "emp-011",
    name: "Ralph Edwards",
    job: "Cleaner",
    joiningDate: "3/22/18",
    totalHoursWork: "288 Hours",
    status: "Active",
  },
  {
    id: "emp-012",
    name: "Kristin Watson",
    job: "Caregivers",
    joiningDate: "10/5/13",
    totalHoursWork: "72 Hours",
    status: "Inactive",
  },
  {
    id: "emp-013",
    name: "Wade Warren",
    job: "Driver",
    joiningDate: "8/17/11",
    totalHoursWork: "544 Hours",
    status: "Active",
  },
  {
    id: "emp-014",
    name: "Leslie Alexander",
    job: "Cleaner",
    joiningDate: "1/11/19",
    totalHoursWork: "156 Hours",
    status: "Inactive",
  },
  {
    id: "emp-015",
    name: "Guy Hawkins",
    job: "Yaya",
    joiningDate: "5/30/16",
    totalHoursWork: "401 Hours",
    status: "Active",
  },
  {
    id: "emp-016",
    name: "Theresa Webb",
    job: "Helper",
    joiningDate: "2/7/12",
    totalHoursWork: "289 Hours",
    status: "Inactive",
  },
  {
    id: "emp-017",
    name: "Devon Lane",
    job: "Driver",
    joiningDate: "9/21/15",
    totalHoursWork: "367 Hours",
    status: "Active",
  },
  {
    id: "emp-018",
    name: "Annette Black",
    job: "Caregivers",
    joiningDate: "7/2/14",
    totalHoursWork: "122 Hours",
    status: "Inactive",
  },
  {
    id: "emp-019",
    name: "Eleanor Pena",
    job: "Cleaner",
    joiningDate: "11/19/13",
    totalHoursWork: "478 Hours",
    status: "Active",
  },
  {
    id: "emp-020",
    name: "Jerome Bell",
    job: "Yaya",
    joiningDate: "6/1/17",
    totalHoursWork: "209 Hours",
    status: "Inactive",
  },
  {
    id: "emp-021",
    name: "Arlene McCoy",
    job: "Driver",
    joiningDate: "12/15/12",
    totalHoursWork: "615 Hours",
    status: "Active",
  },
  {
    id: "emp-022",
    name: "Esther Howard",
    job: "Caregivers",
    joiningDate: "4/25/18",
    totalHoursWork: "99 Hours",
    status: "Inactive",
  },
  {
    id: "emp-023",
    name: "Robert Fox",
    job: "Cleaner",
    joiningDate: "5/18/16",
    totalHoursWork: "350 Hours",
    status: "Active",
  },
  {
    id: "emp-024",
    name: "Courtney Watson",
    job: "Helper",
    joiningDate: "3/3/19",
    totalHoursWork: "185 Hours",
    status: "Active",
  },
];
