export const fraudData = [
  {
    name: "Darlene Robertson",
    activityType: "Fake ID",
    joiningDate: "2016-9-23",
    time: "01:09 am",
    status: "Resolved",
  },
  {
    name: "Cody Fisher",
    activityType: "Spam Messaging",
    joiningDate: "2012-10-28",
    time: "10:41 pm",
    status: "Investigating",
  },
  {
    name: "Savannah Nguyen",
    activityType: "Fake ID",
    joiningDate: "2017-12-4",
    time: "05:49 pm",
    status: "Investigating",
  },
  {
    name: "Floyd Miles",
    activityType: "Spam Messaging",
    joiningDate: "2013-7-27",
    time: "07:13 pm",
    status: "Resolved",
  },
  {
    name: "Jacob Jones",
    activityType: "Fake ID",
    joiningDate: "2012-1-15",
    time: "01:55 pm",
    status: "Investigating",
  },
  {
    name: "Marvin McKinney",
    activityType: "Spam Messaging",
    joiningDate: "2016-3-4",
    time: "01:08 pm",
    status: "Resolved",
  },
  {
    name: "Cameron Williamson",
    activityType: "Fake ID",
    joiningDate: "2017-8-15",
    time: "02:34 am",
    status: "Resolved",
  },
  {
    name: "Courtney Henry",
    activityType: "Fake ID",
    joiningDate: "2016-5-7",
    time: "02:02 am",
    status: "Resolved",
  },

  // +16 more
  {
    name: "Ralph Edwards",
    activityType: "Spam Messaging",
    joiningDate: "2012-10-12",
    time: "11:22 am",
    status: "Investigating",
  },
  {
    name: "Theresa Webb",
    activityType: "Fake ID",
    joiningDate: "2015-4-17",
    time: "09:31 pm",
    status: "Resolved",
  },
  {
    name: "Devon Lane",
    activityType: "Spam Messaging",
    joiningDate: "2016-6-9",
    time: "03:45 am",
    status: "Resolved",
  },
  {
    name: "Kristin Watson",
    activityType: "Fake ID",
    joiningDate: "2018-1-23",
    time: "12:07 pm",
    status: "Investigating",
  },
  {
    name: "Dianne Russell",
    activityType: "Spam Messaging",
    joiningDate: "2013-3-2",
    time: "04:58 pm",
    status: "Resolved",
  },
  {
    name: "Jane Cooper",
    activityType: "Fake ID",
    joiningDate: "2017-7-5",
    time: "08:14 am",
    status: "Resolved",
  },
  {
    name: "Jerome Bell",
    activityType: "Spam Messaging",
    joiningDate: "2014-11-19",
    time: "10:03 pm",
    status: "Investigating",
  },
  {
    name: "Wade Warren",
    activityType: "Fake ID",
    joiningDate: "2011-2-28",
    time: "06:22 am",
    status: "Resolved",
  },
  {
    name: "Leslie Alexander",
    activityType: "Spam Messaging",
    joiningDate: "2019-9-8",
    time: "05:11 pm",
    status: "Investigating",
  },
  {
    name: "Jenny Wilson",
    activityType: "Fake ID",
    joiningDate: "2018-12-1",
    time: "07:40 am",
    status: "Resolved",
  },
  {
    name: "Robert Fox",
    activityType: "Spam Messaging",
    joiningDate: "2015-5-30",
    time: "01:27 pm",
    status: "Investigating",
  },
  {
    name: "Albert Flores",
    activityType: "Fake ID",
    joiningDate: "2016-8-21",
    time: "02:55 am",
    status: "Resolved",
  },
  {
    name: "Annette Black",
    activityType: "Spam Messaging",
    joiningDate: "2013-6-14",
    time: "09:16 am",
    status: "Resolved",
  },
  {
    name: "Bessie Cooper",
    activityType: "Fake ID",
    joiningDate: "2017-10-9",
    time: "04:02 pm",
    status: "Investigating",
  },
  {
    name: "Kathryn Murphy",
    activityType: "Spam Messaging",
    joiningDate: "2012-12-18",
    time: "11:50 am",
    status: "Resolved",
  },
  {
    name: "Guy Hawkins",
    activityType: "Fake ID",
    joiningDate: "2014-1-7",
    time: "08:59 pm",
    status: "Investigating",
  },
];

export const ticketData = [
  {
    id: 123,
    userName: "Darlene Robertson",
    userType: "KindTao",
    issueType: "Profile Issue",
    submittedDate: "2016-09-23",
    status: "Resolved",
  },
  {
    id: 124,
    userName: "Cody Fisher",
    userType: "KindBossing",
    issueType: "Profile Issue",
    submittedDate: "2012-10-28",
    status: "In Progress",
  },
  {
    id: 125,
    userName: "Savannah Nguyen",
    userType: "KindTao",
    issueType: "Profile Issue",
    submittedDate: "2017-12-04",
    status: "In Progress",
  },
  {
    id: 126,
    userName: "Floyd Miles",
    userType: "KindTao",
    issueType: "Payment Issue",
    submittedDate: "2013-07-27",
    status: "Resolved",
  },
  {
    id: 127,
    userName: "Jacob Jones",
    userType: "KindBossing",
    issueType: "Payment Issue",
    submittedDate: "2012-01-15",
    status: "In Progress",
  },
  {
    id: 128,
    userName: "Marvin McKinney",
    userType: "KindBossing",
    issueType: "Fraud Report",
    submittedDate: "2016-03-04",
    status: "Resolved",
  },
  {
    id: 129,
    userName: "Cameron Williamson",
    userType: "KindBossing",
    issueType: "Payment Issue",
    submittedDate: "2017-08-15",
    status: "Resolved",
  },
  {
    id: 130,
    userName: "Courtney Henry",
    userType: "KindTao",
    issueType: "Fraud Report",
    submittedDate: "2016-05-07",
    status: "Resolved",
  },
  {
    id: 131,
    userName: "Esther Howard",
    userType: "KindTao",
    issueType: "Profile Issue",
    submittedDate: "2018-06-12",
    status: "In Progress",
  },
  {
    id: 132,
    userName: "Theresa Webb",
    userType: "KindBossing",
    issueType: "Payment Issue",
    submittedDate: "2015-02-27",
    status: "Resolved",
  },
  {
    id: 133,
    userName: "Ralph Edwards",
    userType: "KindTao",
    issueType: "Fraud Report",
    submittedDate: "2013-09-18",
    status: "Resolved",
  },
  {
    id: 134,
    userName: "Devon Lane",
    userType: "KindBossing",
    issueType: "Profile Issue",
    submittedDate: "2014-04-05",
    status: "In Progress",
  },
  {
    id: 135,
    userName: "Kristin Watson",
    userType: "KindBossing",
    issueType: "Payment Issue",
    submittedDate: "2019-01-23",
    status: "In Progress",
  },
  {
    id: 136,
    userName: "Dianne Russell",
    userType: "KindTao",
    issueType: "Fraud Report",
    submittedDate: "2013-03-02",
    status: "Resolved",
  },
  {
    id: 137,
    userName: "Jane Cooper",
    userType: "KindTao",
    issueType: "Profile Issue",
    submittedDate: "2017-07-05",
    status: "Resolved",
  },
];

export const bulkPartnerAccountData = [
  { name: "Darlene Robertson", email: "abc@gmail.com", status: "Created" },
  { name: "Cody Fisher", email: "abc@gmail.com", status: "Failed" },
  { name: "Savannah Nguyen", email: "abc@gmail.com", status: "Failed" },
  { name: "Floyd Miles", email: "abc@gmail.com", status: "Created" },
  { name: "Jacob Jones", email: "abc@gmail.com", status: "Failed" },
  { name: "Marvin McKinney", email: "abc@gmail.com", status: "Created" },
  { name: "Cameron Williamson", email: "abc@gmail.com", status: "Created" },
  { name: "Courtney Henry", email: "abc@gmail.com", status: "Created" },
  { name: "Ralph Edwards", email: "abc@gmail.com", status: "Failed" },
  { name: "Kristin Watson", email: "abc@gmail.com", status: "Created" },
  { name: "Dianne Russell", email: "abc@gmail.com", status: "Created" },
  { name: "Jane Cooper", email: "abc@gmail.com", status: "Failed" },
  { name: "Devon Lane", email: "abc@gmail.com", status: "Created" },
  { name: "Esther Howard", email: "abc@gmail.com", status: "Failed" },
  { name: "Theresa Webb", email: "abc@gmail.com", status: "Created" },
  { name: "Jerome Bell", email: "abc@gmail.com", status: "Failed" },
  { name: "Wade Warren", email: "abc@gmail.com", status: "Created" },
  { name: "Leslie Alexander", email: "abc@gmail.com", status: "Created" },
  { name: "Jenny Wilson", email: "abc@gmail.com", status: "Failed" },
  { name: "Robert Fox", email: "abc@gmail.com", status: "Created" },
  { name: "Albert Flores", email: "abc@gmail.com", status: "Failed" },
  { name: "Annette Black", email: "abc@gmail.com", status: "Created" },
  { name: "Bessie Cooper", email: "abc@gmail.com", status: "Created" },
  { name: "Kathryn Murphy", email: "abc@gmail.com", status: "Failed" },
  { name: "Ralph Edwards", email: "abc@gmail.com", status: "Failed" },
  { name: "Kristin Watson", email: "abc@gmail.com", status: "Created" },
  { name: "Dianne Russell", email: "abc@gmail.com", status: "Created" },
  { name: "Jane Cooper", email: "abc@gmail.com", status: "Failed" },
  { name: "Devon Lane", email: "abc@gmail.com", status: "Created" },
  { name: "Esther Howard", email: "abc@gmail.com", status: "Failed" },
  { name: "Theresa Webb", email: "abc@gmail.com", status: "Created" },
  { name: "Jerome Bell", email: "abc@gmail.com", status: "Failed" },
  { name: "Wade Warren", email: "abc@gmail.com", status: "Created" },
  { name: "Leslie Alexander", email: "abc@gmail.com", status: "Created" },
  { name: "Jenny Wilson", email: "abc@gmail.com", status: "Failed" },
  { name: "Robert Fox", email: "abc@gmail.com", status: "Created" },
  { name: "Albert Flores", email: "abc@gmail.com", status: "Failed" },
  { name: "Annette Black", email: "abc@gmail.com", status: "Created" },
  { name: "Bessie Cooper", email: "abc@gmail.com", status: "Created" },
  { name: "Kathryn Murphy", email: "abc@gmail.com", status: "Failed" },
];
